### ISSUE TITLE
Github Dependabot &  php-actions/phpunit@v7

### ISSUE THREAD

**Issue by aguilita1** [php-actions/phpunit#71]
**Is there php-actions/phpunit@v7?**  

I have been experimenting with [Github Dependabot](https://github.com/aguilita1/SampleSyncApp/blob/main/.github/dependabot.yml) and it just recommended upgrading to php-actions/phpunit@v7. See pull request [Bump php-actions/phpunit from 4 to 7 in /.github/workflows](https://github.com/aguilita1/SampleSyncApp/pull/17).  The [Github Action Marketplace ](https://github.com/marketplace/actions/phpunit-php-actions) has version 4 as latest.  

I am confused why Dependabot determined version 7 existed and upgrade was recommended. Any insights into your version scheme and how versions are published to Github marketplace would be greatly appreciated.

**Comment by g105b** [comment]
Please see https://github.com/php-actions/phpunit?tab=readme-ov-file#github-actions-releases 

When I originally set this repository up pre-2020, I thought it was a good idea to match the version release of this repository to the corresponding PHPUnit version, but it turned out to not be a good idea at all. I maintained the old versioning scheme until November 2021, but since then all reference to the old releases/tags has been removed.

If you look at https://github.com/php-actions/phpunit/tags it shows all the known git tags for the repository, so I'm not sure where Dependabot is seeing v7 from. I wonder if you know of anywhere else in the git settings that stores a memory of an old tag, or whether this is something that the kind people at @dependabot can step in to answer?

**Comment by aguilita1** [comment]
Thanks for your prompt reply - **I think the issues is `php-action/phpunit` has branches that look like versions**. 

The Github dependabot documentation is light on how it determines the latest version of a Github Action dependency. However their source code indicates it uses [version tags in update checker](https://github.com/dependabot/dependabot-core/blob/main/github_actions/lib/dependabot/github_actions/update_checker.rb) and digging a little deeper it seems to also use branches that look like versions (see the [git_commit_checker](https://github.com/dependabot/dependabot-core/blob/main/common/lib/dependabot/git_commit_checker.rb)).  Note I tested their regex for spotting versions and found version branch `v7` matches but `release-v9` does not match.

I recommend to make the next major version of `php-action/phpunit`, v8.

**Comment by aguilita1** [comment]
BTW, it seems referencing the git SHA for release 4.0.0 provides a workaround for now.

```
    - name: PHPUnit Tests (v4 SHA referenced below)
      uses: php-actions/phpunit@1789d1964b1bfda259b1cb42a72b65299c2cae35
      with:
        version: 9
        bootstrap: vendor/autoload.php
        configuration: tests/phpunit.xml
        args: --coverage-text
```

**Comment by GeraudBourdin** [comment]
> BTW, it seems referencing the git SHA for release 4.0.0 provides a workaround for now.
Works perfectly thanks !

**Comment by g105b** [comment]
Thanks for your suggestions!

I've gone ahead and removed the old branches - they were stale for 4 years anyway, so were not needed. They should no longer get picked up as versions by certain software.
